[upload_bin] support 2 way simultaneously: sshpass + ssh key

diff --git a/upload_bin b/upload_bin
--- a/upload_bin
+++ b/upload_bin
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 if [ $# -lt 2 ]; then
 	echo "Usage: $0 <DEVICE_IP> <FW_BIN>"
@@ -15,13 +15,26 @@ fi
 
 echo Firmware name: "$(basename "$FW_BIN")"
 
-KEY="$HOME/.ssh/id_rsa_ubnt"
-if [ ! -e "$KEY" ]; then
-	ssh-keygen -t rsa -N "" -f "$KEY"
-fi
-
 SSH_OPTION_IGNORE_CHECK="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
 
-sshpass -p ubnt ssh-copy-id $SSH_OPTION_IGNORE_CHECK -i "$KEY".pub ubnt@"$DEVICE_IP" >/dev/null 2>&1
-scp $SSH_OPTION_IGNORE_CHECK -i "$KEY" "$FW_BIN" ubnt@"$DEVICE_IP":/tmp/fwupdate.bin
-[ $? -eq 0 ] && ssh $SSH_OPTION_IGNORE_CHECK -i "$KEY" ubnt@"$DEVICE_IP" /usr/bin/fwupdate -m || echo "FW upload fail!"
+# Methond 1: Simpler way but not preseting scp uploading progress
+# Methond 2: Use ssh key for auth instead of sshpass
+METHOD=2
+
+case $METHOD in
+	1)
+		sshpass -p ubnt scp $SSH_OPTION_IGNORE_CHECK "$FW_BIN" ubnt@"$DEVICE_IP":/tmp/fwupdate.bin
+		sshpass -p ubnt ssh $SSH_OPTION_IGNORE_CHECK ubnt@"$DEVICE_IP" /usr/bin/fwupdate -m || echo "FW upload fail!"
+		;;
+	2)
+		KEY="$HOME/.ssh/id_rsa_ubnt"
+		if [ ! -e "$KEY" ]; then
+			ssh-keygen -t rsa -N "" -f "$KEY"
+		fi
+
+		sshpass -p ubnt ssh-copy-id $SSH_OPTION_IGNORE_CHECK -i "$KEY".pub ubnt@"$DEVICE_IP" >/dev/null 2>&1
+		scp $SSH_OPTION_IGNORE_CHECK -i "$KEY" "$FW_BIN" ubnt@"$DEVICE_IP":/tmp/fwupdate.bin
+		[ $? -eq 0 ] && ssh -i "$KEY" ubnt@"$DEVICE_IP" /usr/bin/fwupdate -m || echo "FW upload fail!"
+		;;
+esac
+
