Use another wcfind, accept no args like gnu find

diff --git a/wcfind_ b/wcfind_
--- a/wcfind_
+++ b/wcfind_
@@ -1,62 +1,70 @@
-#!/bin/sh
+#!/bin/sh -f
+# ----------------------------------------------------------------------------
+# Amarganth Development Environment
+# Copyright (C) 2004, Jeff Hung
+# All rights reserved.
+# ----------------------------------------------------------------------------
+# $Date$
+# $Rev$
+# $Author$
+# ----------------------------------------------------------------------------
+# revid: "@(#) $Id$"
+# ----------------------------------------------------------------------------
 
-# Copyright 2007 Max Bowsher
-# Licensed under the terms Subversion ships under
+__revision=`echo '$Rev$' | cut -d' ' -f2`;
+__rev_date=`echo '$Date$' | cut -d' ' -f2`;
+__pname=`basename $0`;
 
-# Runs the 'find' program, with arguments munged such that '.svn' or 'CVS'
-# working copy administrative directories and their contents are ignored.
+__usage()
+{
+    local ex=0;
+    if [ $# -gt 0 ]; then
+        ex=$1; shift;
+    fi;
+    echo >&2 "\
+    Usage: $__pname [ <grep-option> ... ] <pattern> [ <path> ... ]
 
-optspaths=
-expropts=
-exproptarg=
-exprmain=
-depth=
-somethingseen=
-phase=optspaths
-print=-print
-for option in "$@"; do
-    if [ "$phase" = "optspaths" ]; then
-        case $option in
-            -H|-L|-P) ;;
-            -*|"("*|")"*|,*|!*) phase=exprmain ;;
-            *) ;;
-        esac
-    fi
-    if [ "$exproptarg" = "yes" ]; then
-        exproptarg=
-        phase=expropts
-    fi
-    if [ "$phase" = "exprmain" ]; then
-        case $option in
-            -depth|-d) depth=yes ;;
-            -delete|-exec|-exec|-execdir|-execdir|-fls|-fprint|-fprint0 \
-            |-fprintf|-ok|-print|-okdir|-print0|-printf|-quit|-ls) print= ;;
-        esac
-        case $option in
-            -depth|-d|-noleaf|-mount|-xdev|-warn|-nowarn \
-            |-ignore_readdir_race|-noignore_readdir_race) phase=expropts ;;
-            -maxdepth|-mindepth|-regextype) phase=expropts; exproptarg=yes ;;
-            -follow|-daystart) ;;
-            *) somethingseen=yes
-        esac
-    fi
-    eval "$phase=\"\$$phase \\\"$option\\\"\""
-    if [ "$phase" = "expropts" ]; then
-        phase=exprmain
-    fi
-done
+    Examples:
 
-if [ -z "$somethingseen" ]; then
-    exprmain="$exprmain -print"
-    print=
-fi
+    SHELL> $__pname . -type f -name '*.h' -or -name '*.cpp'
 
-if [ "$depth" = "yes" ]; then
-    eval find $optspaths $expropts \
-    -regex \''.*/\.svn'\' -or -regex \''.*/\.svn/.*'\' \
-    -or -regex \''.*/CVS'\' -or -regex \''.*/CVS/.*'\' \
-    -or '\(' $exprmain '\)' $print
-else
-    eval find $optspaths $expropts '\(' -name .svn -or -name CVS '\)' -prune \
-    -or '\(' $exprmain '\)' $print
-fi
+    SHELL> $__pname . -type f \\
+    \`file-type-patterns.sh lang-cpp \\
+    | xargs -n 1 -I \& echo '-or -name &' \\
+    | xargs echo \\
+    | sed -e s/^-or//\` \\
+    ;
+
+    Revision: r${__revision} (${__rev_date})
+    ";
+    if [ $# -gt 0 ]; then
+        echo >&2 "";
+        echo >&2 "Error: $@";
+    fi;
+    exit $ex;
+}
+
+__path='';
+__find_args='';
+while [ $# -gt 0 ]; do
+    __arg="$1"; shift;
+    if [ -z "$__path" ]; then
+        __path="$__arg";
+    else
+        __find_args="$__find_args $__arg";
+    fi;
+done;
+if [ -z "${__path}" ]; then
+    __usage;
+fi;
+if [ -z "$__find_args" ]; then
+    # jeffhung.20060124:
+    # - Useful to follow after -or to maintain find(1) command-line syntax, but
+    #   is redundant actually.
+    __find_args="-mindepth 0";
+fi;
+
+find "$__path" -type d -regex '.*/\.svn' -prune -or $__find_args \
+| grep -v '.*/\.svn$' \
+;
+
